## Proceso de limpieza en tabla de evaluaciones

#### Importaciones de librerias y analisis general

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import unicodedata as nc

In [3]:
df_evaluaciones = pd.read_csv('./datos_crudos/evaluaciones_dirty.csv')

In [4]:
df_evaluaciones

     id_empleado score_desempeño     comentarios
0            101               7       Aceptable
1            102             NaN       Aceptable
2            103       excelente       Excelente
3            104               6       Excelente
4            105               7       Muy bueno
..           ...             ...             ...
145          246              10       Aceptable
146          247               8             NaN
147          248       excelente  Buen desempeño
148          249               7  Buen desempeño
149          250               7         Regular

[150 rows x 3 columns]

#### Conclusion :
Previo al chequeo general, resulta fundamental validar la vinculación con la tabla de empleados mediante la variable id_empleado. Una vez finalizada la limpieza de dicha tabla, se procede a verificar los IDs registrados en las demás tablas relacionadas, eliminando aquellos que no tengan correspondencia válida. Esto garantiza la integridad referencial de los datos y permite realizar el análisis sobre información consistente y depurada.

#### Eliminacion de ids inexistentes

In [10]:
df_evaluaciones = df_evaluaciones[
    df_evaluaciones['id_empleado'].isin([103,133,152,169,185,214,227,231,248])
]

In [11]:
df_evaluaciones

     id_empleado score_desempeño     comentarios
2            103       excelente       Excelente
32           133              10       Muy bueno
51           152              15             NaN
68           169              15             NaN
84           185               8         Regular
113          214               6       Aceptable
126          227               6  Buen desempeño
130          231       excelente  Buen desempeño
147          248       excelente  Buen desempeño

#### Tareas realizadas :
Dado que la columna comentarios presenta valores nulos e inconsistencias en su redacción, se decide utilizar la variable score_desempeño como referencia principal para el análisis, ya que representa una medición objetiva del desempeño del empleado.

Los comentarios se consideran un campo complementario y opcional, por lo que se procede a estandarizarlos en función del puntaje registrado. De esta manera se logra coherencia entre ambas variables y se facilita el análisis posterior.

### Análisis general

In [14]:
df_evaluaciones.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 2 to 147
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      9 non-null      int64
 1   score_desempeño  9 non-null      object
 2   comentarios      7 non-null      object
dtypes: int64(1), object(2)
memory usage: 288.0+ bytes

In [16]:
df_evaluaciones.shape

(9, 3)

In [25]:
df_evaluaciones.apply(lambda col : col.duplicated().sum())

id_empleado        0
score_desempeño    4
comentarios        3
dtype: int64

In [27]:
df_evaluaciones.isnull().sum()

id_empleado        0
score_desempeño    0
comentarios        2
dtype: int64

### Conclusión : 
Se realiza un chequeo general de la tabla, observando que cuenta con 9 filas y 3 columnas. Durante la revisión se detecta que la variable score_desempeño presenta un tipo de dato incorrecto, encontrándose como object cuando debería ser una variable numérica entera, por lo que se procede a su conversión.

Asimismo, se identifican valores repetidos en las columnas score_desempeño y comentarios, situación esperable dado que una representa una variable cuantitativa discreta y la otra una variable categórica. También se observan valores nulos únicamente en la columna comentarios, lo cual no afecta el análisis ya que se trata de un campo complementario. Por último, se detectan registros donde aparecen valores descriptivos en score_desempeño que corresponden en realidad a la columna comentarios, por lo que se corrigen para mantener coherencia en los tipos de datos.

#### Tratamiento columna 'score_desempeño'

In [28]:
df_evaluaciones['score_desempeño']

2      excelente
32            10
51            15
68            15
84             8
113            6
126            6
130    excelente
147    excelente
Name: score_desempeño, dtype: object

In [30]:
df_evaluaciones.loc[
    df_evaluaciones['score_desempeño'] == 'excelente'
    ,'score_desempeño'
] = '10'

In [41]:
df_evaluaciones

     id_empleado  score_desempeño comentarios
2            103               10   excelente
32           133               10   excelente
51           152               15         NaN
68           169               15         NaN
84           185                8   muy bueno
113          214                6   aceptable
126          227                6   aceptable
130          231               10   excelente
147          248               10   excelente

In [44]:
df_evaluaciones['score_desempeño'] = df_evaluaciones['score_desempeño'].astype('Int64')

In [43]:
df_evaluaciones.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 2 to 147
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      9 non-null      int64
 1   score_desempeño  9 non-null      int64
 2   comentarios      7 non-null      object
dtypes: int64(2), object(1)
memory usage: 288.0+ bytes

#### Tareas realizadas en columna 'score_desempeño'
Se detectan valores de tipo string en la variable score_desempeño, los cuales no corresponden a la escala numérica definida para el análisis. En estos casos, se procede a su conversión al valor numérico equivalente, tomando “excelente” como 10, según los criterios establecidos por la empresa.
Se procede a la conversión de la variable 'score_desempeño' de object a numero entero

Asimismo, la empresa proporcionó una escala de equivalencias entre puntaje y comentarios cualitativos, la cual se utilizará para completar y estandarizar la columna comentarios, garantizando coherencia entre ambas variables.

| Desempeño | comentarios|
| --------- | ---------- |
|    10     |  excelente |
|  9 y 8    |  muy bueno |
|    7      |buen desempeño|
|    6      |  aceptable     |
|  4 y 5    |  regular   |

#### Tratamiento columna 'desempeño'

In [32]:
df_evaluaciones.loc[
    df_evaluaciones['score_desempeño'] == '10'
    ,'comentarios'
] = 'excelente'

In [35]:
df_evaluaciones.loc[
    df_evaluaciones['score_desempeño'] == '8'
    ,'comentarios'
] = 'muy bueno'

In [36]:
df_evaluaciones.loc[
    df_evaluaciones['score_desempeño'] == '6'
    ,'comentarios'

] = 'aceptable'

In [52]:
df_evaluaciones

     id_empleado  score_desempeño comentarios
2            103               10   excelente
32           133               10   excelente
51           152               15        <NA>
68           169               15        <NA>
84           185                8   muy bueno
113          214                6   aceptable
126          227                6   aceptable
130          231               10   excelente
147          248               10   excelente

In [55]:
df_evaluaciones = df_evaluaciones[df_evaluaciones['id_empleado'] != 169 ]

In [57]:
df_evaluaciones = df_evaluaciones[df_evaluaciones['id_empleado'] != 152]

#### Tareas realizadas en columna 'comentarios' :
Se completaron y corrigieron los valores faltantes y existentes en la columna comentarios, tomando como referencia los puntajes de la columna score_desempeño y la tabla de equivalencias proporcionada por la empresa.

El registro de id_empleado 169 (ascenso de Ventas a RRHH) presentaba ausencia total de datos en score_desempeño y comentarios, por lo que se decidió eliminarlo del análisis de desempeño debido a la falta de información objetiva.

Por otro lado, id_empleado 152 corresponde a otra empleada con el mismo nombre pero distinta edad y sector (Ventas). Si bien el registro se mantiene en el dataset original por tratarse de una persona distinta, también se excluye del análisis de desempeño al no contar con métricas evaluativas.

In [58]:
df_evaluaciones

     id_empleado  score_desempeño comentarios
2            103               10   excelente
32           133               10   excelente
84           185                8   muy bueno
113          214                6   aceptable
126          227                6   aceptable
130          231               10   excelente
147          248               10   excelente

In [59]:
df_evaluaciones.to_csv('evaluaciones_limpio.csv',index=False)